<a href="https://colab.research.google.com/github/marchiluana/Arvore-Projeto/blob/master/Base_Pessoas_com_C%C3%A2ncer_no_EUA_Implementa%C3%A7%C3%A3o_do_Algoritmo_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Gerando Modelo de Machine Learning (Classificação)
# Preparação dos Dados e Treinamento do Modelo de Machine Learning

In [ ]:
# Autor: Luana De Marchi Maropo - Data: 23/08/2022 - Aula de Ciência de Dados

In [ ]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [5]:
#Carrega o dataset com os dados para o treinamento e validacao
df_coracao = pd.read_csv("heart.csv", encoding="utf-8")

In [6]:
df_coracao.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [7]:
#Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(df_coracao[['age', 'sex', 'cp', 'trestbps', 'chol' , 'thalach' , 'oldpeak', ]])
#Definição do atributo de classificacao
data_classif = np.array(df_coracao['target'])

In [8]:
# Verificando o formato dos dados
df_coracao.shape

(303, 14)

In [9]:
# Verificando as primeiras linhas do dataset
df_coracao.head(10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   
6   56    0   1       140   294    0        0      153      0      1.3      1   
7   44    1   1       120   263    0        1      173      0      0.0      2   
8   52    1   2       172   199    1        1      162      0      0.5      2   
9   57    1   2       150   168    0        1      174      0      1.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1  
6   0     2       1  
7   0     3       1  
8   0     3       1  
9   0     2       1

In [10]:
# Verificando as últimas linhas do dataset
df_coracao.tail(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0

In [11]:
# Identificando a correlação entre as variáveis
# Correlação não implica causalidade
def plot_corr(df_coracao, size=10):
    corr = df_coracao()    
    fig, ax = plt.subplots(figsize = (size, size))
    ax.matshow(corr)  
    plt.xticks(range(len(corr.columns)), corr.columns) 
    plt.yticks(range(len(corr.columns)), corr.columns) 

In [12]:
# Spliting = 70% para dados de treino e 30% para dados de teste

In [13]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.30)

In [14]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[6.10e+01 1.00e+00 0.00e+00 ... 2.07e+02 1.38e+02 1.90e+00]
 [5.90e+01 1.00e+00 0.00e+00 ... 3.26e+02 1.40e+02 3.40e+00]
 [5.70e+01 1.00e+00 0.00e+00 ... 2.89e+02 1.24e+02 1.00e+00]
 ...
 [5.90e+01 1.00e+00 0.00e+00 ... 1.76e+02 9.00e+01 1.00e+00]
 [6.40e+01 1.00e+00 0.00e+00 ... 2.63e+02 1.05e+02 2.00e-01]
 [6.10e+01 1.00e+00 0.00e+00 ... 1.66e+02 1.25e+02 3.60e+00]]
Conjunto de Validacao
[[3.90e+01 0.00e+00 2.00e+00 1.38e+02 2.20e+02 1.52e+02 0.00e+00]
 [5.80e+01 0.00e+00 3.00e+00 1.50e+02 2.83e+02 1.62e+02 1.00e+00]
 [5.50e+01 1.00e+00 0.00e+00 1.32e+02 3.53e+02 1.32e+02 1.20e+00]
 [6.40e+01 0.00e+00 2.00e+00 1.40e+02 3.13e+02 1.33e+02 2.00e-01]
 [6.00e+01 0.00e+00 0.00e+00 1.50e+02 2.58e+02 1.57e+02 2.60e+00]
 [5.80e+01 1.00e+00 0.00e+00 1.28e+02 2.16e+02 1.31e+02 2.20e+00]
 [5.40e+01 1.00e+00 0.00e+00 1.10e+02 2.39e+02 1.26e+02 2.80e+00]
 [6.20e+01 1.00e+00 1.00e+00 1.20e+02 2.81e+02 1.03e+02 1.40e+00]
 [4.40e+01 1.00e+00 1.00e+00 1

In [15]:
# Imprimindo os resultados
print("{0:0.2f}% nos dados de treino".format((len(x_treino)/len(df_coracao.index)) * 100))
print("{0:0.2f}% nos dados de teste".format((len(x_val)/len(df_coracao.index)) * 100))

69.97% nos dados de treino
30.03% nos dados de teste


In [16]:
# - Aplicando o Algoritmo com o Naive Bayes - GaussianNB.

In [17]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB()

In [18]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("Na Base de Treinamento")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.7688679245283019
Na Base de Treinamento


In [19]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("na Base de Teste e ou Validação")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.8241758241758241
na Base de Teste e ou Validação


In [20]:
from sklearn import metrics

In [22]:
# Métricas

In [21]:
# Criando uma Confusion Matrix
print("Confusion Matrix")

print("{0}".format(metrics.confusion_matrix(y_val, y_pred_val, labels = [1, 0])))
print("")

print("Classification Report")
print(metrics.classification_report(y_val, y_pred_val, labels = [1, 0]))

Confusion Matrix
[[49  6]
 [10 26]]

Classification Report
              precision    recall  f1-score   support

           1       0.83      0.89      0.86        55
           0       0.81      0.72      0.76        36

    accuracy                           0.82        91
   macro avg       0.82      0.81      0.81        91
weighted avg       0.82      0.82      0.82        91



In [23]:
# Criando uma Curva Roc
print("Roc Curve")

# Compute ROC curve and ROC area for each class
#fpr = dict()
#tpr = dict()
#roc_auc = dict()
#for i in range(y_pred_val):
#    fpr[i], tpr[i], _ = roc_curve(y_val, y_pred_val)
#    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
#fpr["micro"], tpr["micro"], _ = roc_curve(y_val.ravel(), y_score.ravel())
#roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

Roc Curve


In [ ]:
# Otimizando o modelo com RandomForest
# Algoritmo 02 - RandomForest - Realizando operações com mais de um Algoritmo de Machine Learning (Classificação)

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
modelo_v2 = RandomForestClassifier(random_state = 42)
modelo_v2.fit(x_treino, y_treino.ravel())

RandomForestClassifier(random_state=42)

In [26]:
# Verificando os dados de treino
rf_predict_train = modelo_v2.predict(x_treino)
print("Exatidão (Accuracy): {0:.4f}".format(metrics.accuracy_score(y_treino, rf_predict_train)))

Exatidão (Accuracy): 1.0000


In [27]:
# Verificando nos dados de teste
rf_predict_test = modelo_v2.predict(x_val)
print("Exatidão (Accuracy): na Base de Teste {0:.4f}".format(metrics.accuracy_score(y_val, rf_predict_test)))
print()

Exatidão (Accuracy): na Base de Teste 0.8242



In [28]:
# Validação do Modelo com a Matrix de Confusão
print("Confusion Matrix")

print("{0}".format(metrics.confusion_matrix(y_val, rf_predict_test, labels = [1, 0])))
print("")

print("Classification Report")
print(metrics.classification_report(y_val, rf_predict_test, labels = [1, 0]))

Confusion Matrix
[[49  6]
 [10 26]]

Classification Report
              precision    recall  f1-score   support

           1       0.83      0.89      0.86        55
           0       0.81      0.72      0.76        36

    accuracy                           0.82        91
   macro avg       0.82      0.81      0.81        91
weighted avg       0.82      0.82      0.82        91



In [32]:
# Regressão Logística
# Terceiro Algorítmo de Machine Learning de Classificação de Dados - 

In [31]:
from sklearn.linear_model import LogisticRegression

In [33]:
# Terceira versão do modelo usando Regressão Logística
modelo_v3 = LogisticRegression(C = 0.7, random_state = 42)
modelo_v3.fit(x_treino, y_treino.ravel())
lr_predict_test = modelo_v3.predict(x_val)

In [34]:
print("Exatidão (Accuracy): na Base de Teste {0:.4f}".format(metrics.accuracy_score(y_val, lr_predict_test)))
print()
print("Classification Report")
print(metrics.classification_report(y_val, lr_predict_test, labels = [1, 0]))

Exatidão (Accuracy): na Base de Teste 0.8791

Classification Report
              precision    recall  f1-score   support

           1       0.88      0.93      0.90        55
           0       0.88      0.81      0.84        36

    accuracy                           0.88        91
   macro avg       0.88      0.87      0.87        91
weighted avg       0.88      0.88      0.88        91



In [35]:
### Resumindo
## Exatidão nos dados Mamíferos de teste

# Modelo usando algoritmo Naive Bayes         = 0.800  => Segunda Execução: 1.0
# Modelo usando algoritmo Random Forest       = 0.800  => Segunda Execução: 1.0 
# Modelo usando algoritmo Regressão Logística = 0.800  => Segunda Execução: 1.0